services:
  catalogue:
    build: ./catalogue
    image: pvraoveera/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb

  mongodb:
    build: ./mongodb
    image: pvraoveera/mongodb:1.0.0  # docker build -t pvraoveera/mongodb:1.0.0, pulls from docker hub
    container_name: mongodb
  
  cart:
    build: ./cart
    image: pvraoveera/cart:1.0.0  # docker build -t pvraoveera/cart:1.0.0, pulls from docker hub
    container_name: cart
    depends_on:
    - redis
    - catalogue

  user:
    build: ./user # It moves to user directory
    image: pvraoveera/user:1.0.0  # docker build -t pvraoveera/user:1.0.0, pulls from docker hub
    container_name: user
    depends_on:
    - redis
    - mongodb
  
  frontend:
    build: ./frontend # It moves to frontend directory
    image: pvraoveera/frontend:1.0.0  # docker build -t pvraoveera/frontend:1.0.0, pulls from docker hub
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
  
  redis:
    image: redis:7.0
    container_name: redis
  
  mysql:
    build: ./mysql
    image: pvraoveera/mysql:1.0.0
    container_name: mysql

  shipping:
    build: ./shipping
    image: pvraoveera/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  
  rabbitmq:
    image: rabbitmq:3
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    container_name: rabbitmq
  
  payment:
    build: ./payment
    image: pvraoveera/payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
    - rabbitmq
    - cart
    - user

networks:
   default:
      driver: bridge
      name: roboshop
      external: false  # if true, you need to create manually roboshop network