services:
  catalogue:
    build:
        dockerfile: catalogue.Dockerfile
    image: pvraoveera/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb

  mongodb:
    build: 
      dockerfile: mongodb.Dockerfile # It moves to mongodb directory
    image: pvraoveera/mongodb:1.0.0  # docker build -t pvraoveera/mongodb:1.0.0, pulls from docker hub
    container_name: mongodb
  
  cart:
    build:
      dockerfile: cart.Dockerfile # It moves to cart directory
    image: pvraoveera/cart:1.0.0  # docker build -t pvraoveera/cart:1.0.0, pulls from docker hub
    container_name: cart
    depends_on:
    - redis

  user:
    build:
      dockerfile: user.Dockerfile # It moves to user directory
    image: pvraoveera/user:1.0.0  # docker build -t pvraoveera/user:1.0.0, pulls from docker hub
    container_name: user
    depends_on:
    - redis
  
  frontend:
    build:
      dockerfile: frontend.Dockerfile # It moves to frontend directory
    image: pvraoveera/frontend:1.0.0  # docker build -t pvraoveera/frontend:1.0.0, pulls from docker hub
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
  
  redis:
    image: redis:7.0
    container_name: redis
  
  mysql:
    build: ./mysql
      #dockerfile: mysql.Dockerfile
    image: pvraoveera/mysql:1.0.0
    container_name: mysql

shipping:
    build: ./shipping
    image: pvraoveera/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql

networks:
   default:
      driver: bridge
      name: roboshop
      external: false  # if true, you need to create manually roboshop network
